"""Markdown report and CSV snapshot writer."""

import logging
import os
from datetime import datetime
import pandas as pd

logger = logging.getLogger(__name__)


def write_report(df: pd.DataFrame, metrics: dict, run_date: str, output_dir: str) -> str:
    """Write a Markdown report and CSV snapshot for the pipeline run.

    Args:
        df: Cleaned DataFrame.
        metrics: KPI metrics dictionary.
        run_date: Date string (YYYY-MM-DD).
        output_dir: Directory to save outputs.

    Returns:
        Path to the Markdown report file.
    """
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # Write CSV snapshot
    csv_path = os.path.join(output_dir, f"data_{run_date}.csv")
    df.to_csv(csv_path, index=False)
    logger.info(f"CSV snapshot saved: {csv_path}")

    # Build Markdown report
    lines = [
        f"# Pipeline Report — {run_date}",
        f"**Generated:** {now}  ",
        "",
        "---",
        "",
        "## Dataset Overview",
        f"- **Total records:** {metrics.get('total_records', 'N/A'):,}",
        f"- **Columns:** {metrics.get('total_columns', 'N/A')}",
        f"- **Fields:** `{'`, `'.join(metrics.get('columns', []))}`",
        "",
    ]

    if "records_by_group" in metrics:
        col = metrics.get("top_group_column", "Group")
        lines += [f"## Records by {col.title()}", ""]
        for key, count in metrics["records_by_group"].items():
            lines.append(f"- **{key}:** {count:,}")
        lines.append("")

    if metrics.get("numeric_summaries"):
        lines += ["## Numeric Field Summaries", ""]
        lines.append("| Field | Mean | Min | Max |")
        lines.append("|---|---|---|---|")
        for col, stats in metrics["numeric_summaries"].items():
            lines.append(f"| {col} | {stats['mean']} | {stats['min']} | {stats['max']} |")
        lines.append("")

    lines += [
        "## Outputs",
        f"- `data_{run_date}.csv` — raw cleaned snapshot",
        f"- `report_{run_date}.md` — this report",
        "",
        "---",
        "",
        "*Generated by Automated Data Pipeline · [Code Alchemist Labs](https://codealchemistlabs.com)*",
    ]

    report_path = os.path.join(output_dir, f"report_{run_date}.md")
    with open(report_path, "w") as f:
        f.write("\n".join(lines))

    logger.info(f"Report written: {report_path}")
    return report_path
