"""Weather pipeline report and CSV snapshot writer."""

import logging
import os
from datetime import datetime
import pandas as pd

logger = logging.getLogger(__name__)


def write_report(df: pd.DataFrame, metrics: dict, run_date: str, output_dir: str, city: str = "") -> str:
    """Write a Markdown weather report and CSV data snapshot.

    Args:
        df: Cleaned DataFrame.
        metrics: KPI metrics dictionary.
        run_date: Date string (YYYY-MM-DD).
        output_dir: Directory to save outputs.
        city: Optional city/location label.

    Returns:
        Path to the Markdown report file.
    """
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    city_label = f" — {city}" if city else ""

    # Write CSV snapshot
    csv_path = os.path.join(output_dir, f"weather_{run_date}.csv")
    df.to_csv(csv_path, index=False)
    logger.info(f"CSV snapshot: {csv_path}")

    lines = [
        f"# Weather Report{city_label}",
        f"**Run date:** {run_date}  ",
        f"**Generated:** {now}",
        "",
        "---",
        "",
        "## Forecast Window",
        f"- **From:** {metrics.get('date_from', 'N/A')}",
        f"- **To:** {metrics.get('date_to', 'N/A')}",
        f"- **Days covered:** {metrics.get('total_days', 'N/A')}",
        "",
        "## Temperature Summary",
        f"- **Avg high:** {metrics.get('avg_high_f', 'N/A')} °F",
        f"- **Avg low:** {metrics.get('avg_low_f', 'N/A')} °F",
        f"- **Hottest day high:** {metrics.get('max_high_f', 'N/A')} °F",
        f"- **Coolest day high:** {metrics.get('min_high_f', 'N/A')} °F",
        f"- **Avg temp range:** {metrics.get('avg_temp_range_f', 'N/A')} °F",
        "",
        "## Precipitation",
        f"- **Total precipitation:** {metrics.get('total_precip_in', 'N/A')} in",
        f"- **Rainy days:** {metrics.get('rainy_days', 'N/A')}",
        "",
        "## Wind",
        f"- **Avg max wind:** {metrics.get('avg_wind_mph', 'N/A')} mph",
        f"- **Strongest gust:** {metrics.get('max_wind_mph', 'N/A')} mph",
        "",
    ]

    if "conditions" in metrics and metrics["conditions"]:
        lines += ["## Sky Conditions", ""]
        for cond, days in metrics["conditions"].items():
            lines.append(f"- **{cond}:** {days} day(s)")
        lines.append("")

    # Daily detail table
    date_col = "date" if "date" in df.columns else None
    if date_col:
        lines += ["## Daily Detail", ""]
        lines.append("| Date | High (°F) | Low (°F) | Precip (in) | Wind Max (mph) | Condition |")
        lines.append("|---|---|---|---|---|---|")
        for _, row in df.iterrows():
            date = str(row["date"].date()) if pd.notna(row.get("date")) else "—"
            hi = f"{row['temp_max_f']:.1f}" if "temp_max_f" in row and pd.notna(row["temp_max_f"]) else "—"
            lo = f"{row['temp_min_f']:.1f}" if "temp_min_f" in row and pd.notna(row["temp_min_f"]) else "—"
            precip = f"{row['precip_in']:.2f}" if "precip_in" in row and pd.notna(row["precip_in"]) else "—"
            wind = f"{row['wind_max_mph']:.1f}" if "wind_max_mph" in row and pd.notna(row["wind_max_mph"]) else "—"
            cond = row.get("condition", "—")
            lines.append(f"| {date} | {hi} | {lo} | {precip} | {wind} | {cond} |")
        lines.append("")

    lines += [
        "## Outputs",
        f"- `weather_{run_date}.csv` — daily data snapshot",
        f"- `report_{run_date}.md` — this report",
        "",
        "---",
        "",
        "*Generated by Automated Data Pipeline · [Code Alchemist Labs](https://codealchemistlabs.com)*",
    ]

    report_path = os.path.join(output_dir, f"report_{run_date}.md")
    with open(report_path, "w") as f:
        f.write("\n".join(lines))

    logger.info(f"Report written: {report_path}")
    return report_path
